// src/utils/exportUtils.ts
import { DbService } from '../services/dbService';
import { useTranslation } from 'react-i18next';

interface CurrentBenchmarkData {
  prompt: string;
  model1: string;
  model2: string;
  output1: string;
  output2: string;
  tps1: number;
  tps2: number;
  ttft1: number;
  ttft2: number;
}

export const generateMarkdownReport = (data: CurrentBenchmarkData): string => {
  return `# 📊 PromptDeck Benchmark Report

**Prompt:**
> ${data.prompt}

## ⚡ Performance Summary
| Metric | ${data.model1} | ${data.model2} |
| :--- | :--- | :--- |
| **Tokens / Sec (TPS)** | **${data.tps1 ? data.tps1.toFixed(2) : 'N/A'}** tok/s | **${data.tps2 ? data.tps2.toFixed(2) : 'N/A'}** tok/s |
| **Time To First Token (TTFT)** | ${data.ttft1 ? data.ttft1 + ' ms' : 'N/A'} | ${data.ttft2 ? data.ttft2 + ' ms' : 'N/A'} |

---

## 📝 Model Outputs

### 🤖 Model 1: \`${data.model1}\`
${data.output1 || '_No output_'}

---

### 🤖 Model 2: \`${data.model2}\`
${data.output2 || '_No output_'}

---
*Generated by PromptDeck*
`;
};

export const copyHistoryAsJson = async (): Promise<boolean> => {
  const { t } = useTranslation();
  try {
    const history = await DbService.getHistory();

    if (!history || history.length === 0) {
      alert(t("export.noHistoryToExport"));
      return false;
    }

    const jsonString = JSON.stringify(history, null, 2);
    await navigator.clipboard.writeText(jsonString);
    return true;
  } catch (error) {
    console.error('Failed to copy history JSON:', error);
    alert(t("export.copyJsonError"));
    return false;
  }
};