// src/utils/exportUtils.ts
import { DbService, BenchmarkResult } from '../services/dbService';
import { useTranslation } from 'react-i18next';

interface CurrentBenchmarkData {
  prompt: string;
  results: BenchmarkResult[];
}

export const generateMarkdownReport = (data: CurrentBenchmarkData): string => {
  const tableHeader = `| Metric | ${data.results.map((r) => r.model).join(' | ')} |`;
  const tableDivider = `| :--- | ${data.results.map(() => ':---').join(' | ')} |`;
  const tpsRow = `| **Tokens / Sec (TPS)** | ${data.results
    .map((r) => `**${r.tps ? r.tps.toFixed(2) : 'N/A'}** tok/s`)
    .join(' | ')} |`;
  const ttftRow = `| **Time To First Token (TTFT)** | ${data.results
    .map((r) => (r.ttft ? `${r.ttft} ms` : 'N/A'))
    .join(' | ')} |`;

  const outputSections = data.results
    .map(
      (r, i) => `
### 🤖 Model ${i + 1}: \`${r.model}\`
${r.output || '_No output_'}
`
    )
    .join('\n---\n');

  return `# 📊 PromptDeck Benchmark Report

**Prompt:**
> ${data.prompt}

## ⚡ Performance Summary
${tableHeader}
${tableDivider}
${tpsRow}
${ttftRow}

---

## 📝 Model Outputs
${outputSections}

---
*Generated by PromptDeck*
`;
};

export const copyHistoryAsJson = async (): Promise<boolean> => {
  const { t } = useTranslation();
  try {
    const history = await DbService.getHistory();

    if (!history || history.length === 0) {
      alert(t("export.noHistoryToExport"));
      return false;
    }

    const jsonString = JSON.stringify(history, null, 2);
    await navigator.clipboard.writeText(jsonString);
    return true;
  } catch (error) {
    console.error('Failed to copy history JSON:', error);
    alert(t("export.copyJsonError"));
    return false;
  }
};