// src/utils/exportUtils.ts
import { DbService, BenchmarkResult } from '../services/dbService';

interface CurrentBenchmarkData {
  prompt: string;
  results: BenchmarkResult[];
}

function formatTpsCell(r: BenchmarkResult): string {
  if (!r.tps) return 'N/A';
  const value = r.tps.toFixed(2);
  return r.tpsEstimated ? `~${value} tok/s (estimated)` : `**${value}** tok/s`;
}

export const generateMarkdownReport = (data: CurrentBenchmarkData): string => {
  const tableHeader = `| Metric | ${data.results.map((r) => r.model).join(' | ')} |`;
  const tableDivider = `| :--- | ${data.results.map(() => ':---').join(' | ')} |`;
  const tpsRow = `| **Tokens / Sec (TPS)** | ${data.results.map(formatTpsCell).join(' | ')} |`;
  const ttftRow = `| **Time To First Token (TTFT)** | ${data.results
    .map((r) => (r.ttft ? `${r.ttft} ms` : 'N/A'))
    .join(' | ')} |`;

  const outputSections = data.results
    .map(
      (r, i) => `
### 🤖 Model ${i + 1}: \`${r.model}\`
${r.output || '_No output_'}
`
    )
    .join('\n---\n');

  const hasEstimated = data.results.some((r) => r.tpsEstimated);
  const footnote = hasEstimated
    ? '\n> ~ = estimated TPS (server did not report token usage).\n'
    : '';

  return `# 📊 PromptDeck Benchmark Report

**Prompt:**
> ${data.prompt}

## ⚡ Performance Summary
${tableHeader}
${tableDivider}
${tpsRow}
${ttftRow}
${footnote}
---

## 📝 Model Outputs
${outputSections}

---
*Generated by PromptDeck*
`;
};

export const copyHistoryAsJson = async (): Promise<boolean> => {
  try {
    const history = await DbService.getHistory();

    if (!history || history.length === 0) {
      alert('No history records to export.');
      return false;
    }

    const jsonString = JSON.stringify(history, null, 2);
    await navigator.clipboard.writeText(jsonString);
    return true;
  } catch (error) {
    console.error('Failed to copy history JSON:', error);
    alert('Failed to copy history JSON.');
    return false;
  }
};

function csvEscape(value: string | number | null | undefined): string {
  const s = value == null ? '' : String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/**
 * Exports the full benchmark history as a CSV file (one row per model result).
 * Downloads via a Blob URL so it works in both Tauri and plain web builds.
 * Returns false when there is nothing to export.
 */
export const exportHistoryAsCsv = async (): Promise<boolean> => {
  try {
    const history = await DbService.getHistory();
    if (!history || history.length === 0) return false;

    const header = ['run_id', 'created_at', 'prompt', 'model', 'tps', 'tps_estimated', 'ttft_ms', 'winner_model', 'output'];
    const lines = [header.join(',')];
    for (const record of history) {
      for (const r of record.results) {
        lines.push(
          [
            csvEscape(record.id),
            csvEscape(record.created_at),
            csvEscape(record.prompt),
            csvEscape(r.model),
            csvEscape(r.tps),
            csvEscape(r.tpsEstimated ? 1 : 0),
            csvEscape(r.ttft),
            csvEscape(record.winnerModel),
            csvEscape(r.output),
          ].join(',')
        );
      }
    }

    const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `promptdeck-history-${Date.now()}.csv`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    return true;
  } catch (error) {
    console.error('Failed to export history CSV:', error);
    return false;
  }
};
